/**
 * index — OKF progressive-disclosure index generator (§6).
 *
 *   - Each non-empty subdirectory of the bundle root gets an index.md catalog:
 *     bullets `* [Title](file.md) - description` from each concept's frontmatter.
 *   - Indexes are reserved files: NO frontmatter (only the bundle-root index.md
 *     carries frontmatter, and only okf_version — INV-2).
 *   - The root index.md links every sub-index inside a managed marker block;
 *     prose outside the block is preserved.
 *   - Output is deterministic (sorted by filename) so reruns produce no diff.
 */

import fs from 'node:fs';
import path from 'node:path';
import { DEFAULT_CONFIG, type OkfConfig } from './config.js';
import { parseFrontmatter } from './frontmatter.js';

export const GENERATED_MARK = '<!-- generated by okf:index — do not edit; run `pnpm okf:index` -->';
export const ROOT_BLOCK_START = '<!-- okf:index:start -->';
export const ROOT_BLOCK_END = '<!-- okf:index:end -->';

interface ConceptMeta {
  file: string; // basename, e.g. SPEC-A11Y-001.md
  title: string;
  description?: string;
  type?: string;
}

function readMeta(filePath: string): ConceptMeta {
  const content = fs.readFileSync(filePath, 'utf-8');
  const file = path.basename(filePath);
  const meta: ConceptMeta = { file, title: path.basename(filePath, '.md') };
  const fm = parseFrontmatter(content);
  if (!fm || 'error' in fm) return meta; // unparseable is `okf check`'s problem (RF-2)
  const data = fm.data as Record<string, unknown> | null;
  if (typeof data?.['title'] === 'string' && data['title'].trim()) meta.title = data['title'];
  if (typeof data?.['description'] === 'string' && data['description'].trim()) {
    meta.description = data['description'];
  }
  if (typeof data?.['type'] === 'string' && data['type'].trim()) meta.type = data['type'];
  return meta;
}

// Non-empty = has ≥1 direct non-reserved .md (same rule as `okf check` RF-8)
function listSubdirs(bundleRoot: string, reserved: Set<string>): string[] {
  return fs
    .readdirSync(bundleRoot, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((dir) => conceptFiles(path.join(bundleRoot, dir), reserved).length > 0)
    .sort();
}

function conceptFiles(dir: string, reserved: Set<string>): string[] {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isFile() && e.name.endsWith('.md') && !reserved.has(e.name))
    .map((e) => e.name)
    .sort();
}

function subIndexContent(bundleRoot: string, sub: string, reserved: Set<string>): string {
  const dir = path.join(bundleRoot, sub);
  const bullets = conceptFiles(dir, reserved).map((f) => {
    const meta = readMeta(path.join(dir, f));
    return meta.description
      ? `* [${meta.title}](${f}) - ${meta.description}`
      : `* [${meta.title}](${f})`;
  });
  return [GENERATED_MARK, '', `# ${sub}/`, '', ...bullets, ''].join('\n');
}

function rootBlockContent(bundleRoot: string, subdirs: string[], reserved: Set<string>): string {
  const lines = subdirs.map((sub) => {
    const files = conceptFiles(path.join(bundleRoot, sub), reserved);
    const types = [
      ...new Set(
        files
          .map((f) => readMeta(path.join(bundleRoot, sub, f)).type)
          .filter((t): t is string => typeof t === 'string'),
      ),
    ].sort();
    const typeNote = types.length > 0 ? ` · type: ${types.join(', ')}` : '';
    return `- **[${sub}/](/${sub}/index.md)** — ${files.length} concepto${files.length === 1 ? '' : 's'}${typeNote}`;
  });
  return lines.join('\n');
}

function rootIndexContent(bundleRoot: string, subdirs: string[], reserved: Set<string>): string {
  const rootIndex = path.join(bundleRoot, 'index.md');
  const current = fs.readFileSync(rootIndex, 'utf-8');
  const start = current.indexOf(ROOT_BLOCK_START);
  const end = current.indexOf(ROOT_BLOCK_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `okf index: root index.md lacks the managed block markers ` +
        `${ROOT_BLOCK_START} … ${ROOT_BLOCK_END}`,
    );
  }
  const before = current.slice(0, start + ROOT_BLOCK_START.length);
  const after = current.slice(end);
  return `${before}\n${rootBlockContent(bundleRoot, subdirs, reserved)}\n${after}`;
}

/** Desired content per target file (bundle-relative path → content). */
export function buildIndexes(
  bundleRoot: string,
  config: OkfConfig = DEFAULT_CONFIG,
): Map<string, string> {
  const reserved = new Set(config.reserved);
  const out = new Map<string, string>();
  const subdirs = listSubdirs(bundleRoot, reserved);
  for (const sub of subdirs) {
    out.set(path.join(sub, 'index.md'), subIndexContent(bundleRoot, sub, reserved));
  }
  out.set('index.md', rootIndexContent(bundleRoot, subdirs, reserved));
  return out;
}

/** Write stale indexes; returns the bundle-relative paths that changed. */
export function applyIndexes(bundleRoot: string, config: OkfConfig = DEFAULT_CONFIG): string[] {
  const changed: string[] = [];
  for (const [rel, content] of buildIndexes(bundleRoot, config)) {
    const full = path.join(bundleRoot, rel);
    const current = fs.existsSync(full) ? fs.readFileSync(full, 'utf-8') : null;
    if (current !== content) {
      fs.writeFileSync(full, content, 'utf-8');
      changed.push(rel);
    }
  }
  return changed.sort();
}

/** Returns the bundle-relative paths whose on-disk content is stale/missing. */
export function checkIndexes(bundleRoot: string, config: OkfConfig = DEFAULT_CONFIG): string[] {
  const stale: string[] = [];
  for (const [rel, content] of buildIndexes(bundleRoot, config)) {
    const full = path.join(bundleRoot, rel);
    if (!fs.existsSync(full) || fs.readFileSync(full, 'utf-8') !== content) stale.push(rel);
  }
  return stale.sort();
}

/** CLI runner for `okf index [--check]`. */
export function runIndex(bundleRoot: string, config: OkfConfig, checkMode: boolean): number {
  if (checkMode) {
    const stale = checkIndexes(bundleRoot, config);
    if (stale.length > 0) {
      for (const rel of stale) console.error(`[okf-index] STALE ${rel}`);
      console.error('[okf-index] FAIL: indexes out of date — run `okf index`.');
      return 1;
    }
    console.log('[okf-index] OK — all indexes up to date.');
    return 0;
  }

  const changed = applyIndexes(bundleRoot, config);
  for (const rel of changed) console.log(`[okf-index] wrote ${rel}`);
  console.log(`[okf-index] ${changed.length} file(s) updated.`);
  return 0;
}
